[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
solc = "0.8.20"
evm_version = "shanghai"
optimizer = true
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
